@startuml battle

skinparam PackageStyle rectangle
hide footer

:Logined userA: as userA
:Logined userB: as userB
boundary canvasA
boundary canvasB

rectangle UserA_turtle {
    userA -right-> (Input Instruction)
    (Input Instruction) .down-> (Command line parser): send request
    (Command line parser) .down-> (Command line executer): valid
    (Command line executer) -down-> canvasA: draw
}

rectangle UserB_turtle {
    userB -left-> (Input Instruction')

    (Input Instruction') .down-> (Command line parser'): send request
    (Command line parser') .down-> (Command line executer'): valid
    (Command line executer') -down-> canvasB: draw
}

canvasA -down-> (Grading module)
canvasB -down-> (Grading module)

(Grading module) -down-> (Get Winner)

@enduml