@startuml cooperation

skinparam PackageStyle rectangle
hide footer

:Logined userA: as userA
:Logined userB: as userB
boundary canvas

rectangle Single_turtle {
    userA -right-> (Input Instruction)
    userB -left-> (Input Instruction)

    (Input Instruction) .down-> (Command line parser): send request
    (Command line parser) .down-> (Command line executer): valid
    (Command line executer) -down-> canvas: draw
}

@enduml