@startuml match-module

skinparam PackageStyle rectangle
hide footer

:Logined userA: as userA
:Logined userB: as userB

rectangle Match-module {
    userA -right-> (Matching request): send
    userB -left-> (Matching request): send
    (Matching request) .down-> (Confirm): wait user to confirm
    (Confirm) .down-> (Matching success): both confirmed
}


@enduml