@startuml single-end

skinparam PackageStyle rectangle

hide footer
Actor customer
boundary canvas

rectangle CMD_LINE_MODE {
    customer -up-> (Input instruction): command line mode
    (Input instruction) .right-> (Command line parser): ENTER
    (Command line parser) .right-> (Command line executer): valid
    (Command line executer) -down-> canvas: draw
}

rectangle CMD_FILE_MODE {
    customer -down-> (Import\Edit file): command file mode
    (Import\Edit file) .right-> (LOGO Interpreter): run
    (LOGO Interpreter) .right-> (Command file executer): compile success
    (Command file executer) -up-> canvas: draw
    (Import\Edit file) .down-> (Set breakpoint): debug
    (Set breakpoint) .up-> (LOGO Interpreter): compile
    (LOGO Interpreter) .down-> (Step to run)
    note right of (Step to run): Will draw on canvas as well
}

@enduml