@startuml user-module

skinparam PackageStyle rectangle

Actor customer
note left of customer: 游客
Actor user #Green
note right of user: 已登录
Actor newuser #Blue
note right of newuser: 新账户

usecase (填写注册表单) as register <<register>>
usecase (填写账户密码) as login <<login>>

customer -up-> register
register -right-> (Register API)
(Register API) -right-> newuser

customer -down-> login
login -right-> (Login API)
(Login API) -right-> user: success

@enduml